// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DbRlBseCMwTqBfzT3Cio_o2OnhV-Fmw',
    appId: '1:253700180927:web:8dfe11cb87d8c27f16af0a',
    messagingSenderId: '253700180927',
    projectId: 'appointment-fatec-115dc',
    authDomain: 'appointment-fatec-115dc.firebaseapp.com',
    storageBucket: 'appointment-fatec-115dc.appspot.com',
    measurementId: 'G-WKWTMJ9J8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprJlEY6GQJr0qtlqioGloq6hbi0dGRVA',
    appId: '1:253700180927:android:ac21199cfb177bc616af0a',
    messagingSenderId: '253700180927',
    projectId: 'appointment-fatec-115dc',
    storageBucket: 'appointment-fatec-115dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqIhlAwRzrggAQ7V2o5gLEeQitVfYpZo',
    appId: '1:253700180927:ios:ed7b5607d768e03d16af0a',
    messagingSenderId: '253700180927',
    projectId: 'appointment-fatec-115dc',
    storageBucket: 'appointment-fatec-115dc.appspot.com',
    iosClientId: '253700180927-iq8nisk81bk1p99ur5tp1t8u5iap3n81.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment',
  );
}
